<?php
/**
 * Created by PhpStorm.
 * User: stevenwilson
 * Date: 10/05/2017
 * Time: 15:59
 */
function migration_epubs_uninstall()
{
    Drupal::configFactory()->getEditable('migrate_plus.migration.epubs_epub_data')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.epubs_file')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.epubs_image')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.epubs_node_data')->delete();
    drupal_set_message(t('migrate_epubs settings removed'), 'status', TRUE);
}