version: "3"

services:
  cypress:
    image: cypress/included:6.3.0
    depends_on:
      - prisoner-content-hub-frontend
    entrypoint: |
      /bin/bash  -c "\
        npm init -y  && \
        npm install --save-dev cypress-cucumber-preprocessor && \
        cypress run"
    working_dir: /test
    volumes:
      - ../prisoner-content-hub-frontend/cypress/:/test/cypress/
      - ../prisoner-content-hub-frontend/cypress.json:/test/cypress.json
    networks:
      - prisoner_content_hub

  prisoner-content-hub-backend:
    image: "quay.io/hmpps/prisoner-content-hub-backend:${BACKEND_IMAGE_VERSION}"

  prisoner-content-hub-frontend:
    image: "quay.io/hmpps/prisoner-content-hub-frontend:${FRONTEND_IMAGE_VERSION}"
