apiVersion: v1
kind: Service
metadata:
  name: {{ include "prisoner-content-hub.fullname" . }}-{{ .Values.nprrelay.name }}
  labels:
    {{- include "prisoner-content-hub.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    {{- include "prisoner-content-hub.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prisoner-content-hub.fullname" . }}-{{ .Values.nprrelay.name }}
  labels:
    {{- include "prisoner-content-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nprrelay.replicaCount }}
  selector:
    matchLabels:
      {{- include "prisoner-content-hub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prisoner-content-hub.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.nprrelay.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status-json.xsl
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /status-json.xsl
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: icecast-config
              mountPath: "/etc/icecast"
              readOnly: true
      volumes:
      - name: icecast-config
        secret:
          secretName: icecast.xml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nprrelay.configMapName }}
  labels:
    {{- include "prisoner-content-hub.labels" . | nindent 4 }}
data:  
  externalUrl: {{ include "prisoner-content-hub.externalHost" . }}/{{ .Values.nprrelay.path }}/stream.ogg
