<?php

use Drupal\moj_lang_welsh\Controller\WelshTranslationsController;

function moj_lang_welsh_install()
{
  $WelshTranslationsController = new WelshTranslationsController();
  $WelshTranslationsController->init();
}

function moj_lang_welsh_uninstall()
{
  Drupal::configFactory()->getEditable('moj_lang_welsh.settings')->delete();
  drupal_set_message(t('moj_lang_welsh modules removed'), 'status', TRUE);
}
