<?php

/**
 * @file
 * The core module that manages content archiving within the system.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Database;

/**
 * Implements hook_form_FORM_ID_alter().*
 */
function moj_archive_content_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
	$form_ids = array(
		'node_moj_video_item_edit_form',
		'node_moj_video_collection_edit_form',
		'node_moj_radio_item_edit_form',
		'node_moj_faq_item_edit_form',
		'node_moj_pdf_item_edit_form'
	);

	if (in_array($form_id, $form_ids))
	{
		$node = $form_state->getFormObject()->getEntity();

		if ($node->field_moj_archived->value == 1)
		{
			$form['actions']['unarchive_content'] = array(
				'#type' => 'submit',
				'#value' => t('Unarchive'),
				'#submit' => array('moj_unarchive_content_submit'),
			);
		} else
		{
			$form['actions']['archive_content'] = array(
				'#type' => 'submit',
				'#value' => t('Archive'),
				'#submit' => array('moj_archive_content_submit'),
			);
		}
	}

	return $form;
}

/**
 * Handles submitting radio node edit form via archive button
 */
function moj_archive_content_submit(array &$form, FormStateInterface $form_state)
{
	//Set archived field to true 
	$node = $form_state->getFormObject()->getEntity();
	set_archived($node, 1);

	drupal_set_message($node->title->value . ' has been successfully archived');
	return new Symfony\Component\HttpFoundation\RedirectResponse('/admin/content');
}

/**
 * Handles submitting radio node edit form via unarchive button
 */
function moj_unarchive_content_submit(array &$form, FormStateInterface $form_state)
{
	//Set archived field to false
	$node = $form_state->getFormObject()->getEntity();
	set_archived($node, 0);

	drupal_set_message($node->title->value . ' has been successfully unarchived');
	return new Symfony\Component\HttpFoundation\RedirectResponse('/admin/content');
}

/*
 * Updates archived and published status of node
 */

function set_archived(\Drupal\node\NodeInterface $node, $archived)
{
	$node->field_moj_archived->value = $archived;
	$node->status = !$archived;
	$node->save();
}
