<?php
/**
 * Created by PhpStorm.
 * User: stevenwilson
 * Date: 15/05/2017
 * Time: 14:29
 */
function migration_audios_uninstall()
{
    Drupal::configFactory()->getEditable('migrate_plus.migration.audios_audio')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.audios_cat_image')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.audios_node_data')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.audios_cats')->delete();
    drupal_set_message(t('Audio migration settings removed'), 'status', true);
}