#!/bin/bash

set -e

source /etc/docker-decomposed-secrets.sh

exec docker run --rm -it --name hub-drush \
  --link hub-db --link hub-memcache \
  -e HUB_DB_ENV_MYSQL_DATABASE=hubdb \
  -e HUB_DB_ENV_MYSQL_USER=$MYSQL_USER \
  -e HUB_DB_ENV_MYSQL_PASSWORD=$MYSQL_PASSWORD \
  -e HUB_DB_PORT_3306_TCP_ADDR=hub-db \
  -v hub_be_code:/var/www/html \
  drupaldocker/drush \
  drush --root=/var/www/html $@
