<?php
/**
 * Created by PhpStorm.
 * User: stevenwilson
 * Date: 15/05/2017
 * Time: 14:29
 */
function migration_pdfs_uninstall()
{
    Drupal::configFactory()->getEditable('migrate_plus.migration.pdfs_file')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.pdfs_cat_image')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.pdfs_node_data')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.pdfs_cats')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.pdfs_sub_cats')->delete();
    drupal_set_message(t('PDF migration settings removed'), 'status', TRUE);
}