nameOverride: ""
fullnameOverride: ""

tier: frontend

image:
  repository: mojdigitalstudio/prisoner-content-hub-nprrelay
  pullPolicy: IfNotPresent
  tag: latest

application:
  port: 8000

nprrelay:
  name: npr-live
  path: npr-live
  replicaCount: 2
  maxReplicaCount: 3

ingress:
  enabled: true
  tlsEnabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
