nameOverride: ""
fullnameOverride: ""

tier: frontend

image:
  repository: mojdigitalstudio/prisoner-content-hub-nprrelay
  pullPolicy: IfNotPresent
  tag: latest

application:
  port: 8000
  liveness:
    endpoint: /status-json.xsl
    delaySeconds: 10
    timeoutSeconds: 5
  readiness:
    endpoint: /status-json.xsl
    delaySeconds: 10
    timeoutSeconds: 5

nprrelay:
  name: npr-live
  servicePort: 80
  path: npr-live
  replicaCount: 2
  maxReplicaCount: 3
  secretName: icecast.xml

slack:
  secretName: slack-webhook

service:
  type: ClusterIP
  clusterIP: None

ingress:
  enabled: true
  tlsEnabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
