nameOverride: ""
fullnameOverride: ""

tier: frontend

image:
  repository: mojdigitalstudio/prisoner-content-hub-nprrelay
  pullPolicy: IfNotPresent
  tag: latest

application:
  port: 8000
  liveness:
    endpoint: /status-json.xsl
    delaySeconds: 10
    timeoutSeconds: 5
  readiness:
    endpoint: /status-json.xsl
    delaySeconds: 10
    timeoutSeconds: 5

nprrelay:
  name: npr-live
  servicePort: 80
  path: npr-live
  replicaCount: 2
  maxReplicaCount: 3
  secretName: icecast.xml

slack:
  secretName: slack-webhook

service:
  type: ClusterIP
  clusterIP: None

ingress:
  enabled: true
  tlsEnabled: true
  allowed:
    sheffieldoffice: "217.33.148.210/29"
    mojvpn: "81.134.202.29/32"
    mojvpn-sheffield-egress: "212.137.36.230/32"
    health-kick: "35.177.252.195/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    moj-official: "51.149.250.0/24"
    moj-official-globalprotect-alpha: "35.176.93.186/32"
    ark-data-center-1: "62.25.109.197/32"
    ark-data-center-2: "195.92.38.16/28"
    ark-data-center-3: "195.59.75.0/24"
    ark-data-center-4: "194.33.192.0/25"
    ark-data-center-5: "194.33.193.0/25"
    ark-data-center-6: "194.33.196.0/25"
    ark-data-center-7: "194.33.197.0/25"
    pfs-egress-dp-primary: "18.130.83.42/32"
    pfs-egress-dp-secondary: "52.56.168.163/32"
    pfs-egress-public-ip-1: "51.132.208.67/32"
    pfs-egress-public-ip-2: "51.132.208.80/32"
    pfs-egress-public-ip-3: "51.132.208.113/32"
    pfs-egress-public-ip-4: "51.132.208.122/32"
    blocka: "51.143.132.235/32" # mnop let rd know when removed
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
