# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "512"
  end

  config.vm.provision "shell",
    inline: "apt-get install -y python"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.host_vars = {
      default: {
        env: "dev"
      }
    }
    ansible.groups = {
      bounce: ["default"]
    }
  end
end
