<?php
/**
 * Created by PhpStorm.
 * User: stevenwilson
 * Date: 15/05/2017
 * Time: 14:29
 */
function migration_radios_uninstall()
{
    Drupal::configFactory()->getEditable('migrate_plus.migration.radios_radio')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.radios_cat_image')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.radios_node_data')->delete();
    Drupal::configFactory()->getEditable('migrate_plus.migration.radios_cats')->delete();
    drupal_set_message(t('radio migration settings removed'), 'status', true);
}